---
title: "Proyecto final"
author: "Arturo y valentina"
format: pdf
editor: visual
---

```{r}
install.packages("pacman")
library(pacman)
p_load("ggplot2", "readr", "dplyr", "stats")
```

```{r}
#Abrimos la base de datos
IEA <- read.csv("IEA.csv")
head(IEA)
```

```{r}
colnames(IEA)[3] <- "emissions"
#La columna emisiones tiene las unidades de kilotoneladas (kt)
```

Gráfico emisiones por región.

```{r}
# Sumamos las emisiones de cada región
resumen <- aggregate(IEA$emissions, by = list(Region = IEA$region), sum)
resumen <- resumen[-9,] #Eliminar la suma total
colnames(resumen) <- c("Region", "Emissions")

# Producimos el gráfico
ggplot(data = resumen, aes(x = reorder(Region, Emissions), y = Emissions)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Emisiones por Región",
       x = "Región",
       y = "Emisiones (kt)") +
  theme_minimal()

```

Gráfico por países con mayor y menor emisión

```{r}
# Limiamos la base de datos
IEA_limpio <- IEA %>% filter(!is.na(country))

# Ordenar los datos según las emisiones de cada país
IEA_ordenado <- IEA_limpio %>% arrange(desc(emissions))


```

```{r}
# Seleccionar los países más emisores 
top_paises <- head(IEA_ordenado, 10) %>% arrange(desc(emissions))

# Gráfico para los países más emisores
grafico_top <- ggplot(top_paises, aes(x = reorder(country, emissions), y = emissions)) +
  geom_bar(stat = "identity", fill = "red") +
  coord_flip() +
  labs(title = "Top Países Más Emisores",
       x = "País",
       y = "Emisiones (kt)") +
  theme_minimal()

print(grafico_top)

```


```{r}
# Seleccionar los países menos emisores 
bottom_paises <- tail(IEA_ordenado[IEA_ordenado$emissions > 0,], 10) %>% arrange(desc(emissions))
# Gráfico para los países menos emisores
grafico_bottom <- ggplot(bottom_paises, aes(x = reorder(country, emissions), y = emissions))+
  geom_bar(stat = "identity", fill = "green") +
  coord_flip() +
  labs(title = "Top Países Menos Emisores",
       x = "País",
       y = "Emisiones (kt)") +
  theme_minimal()

print(grafico_bottom)
```

Análisis de regresion lineal para determinar si la emsión de los países depende de la región en la que se encuentra.

```{r}

# Convertir la columna de regiones a un factor para análisis categórico
IEA_limpio$region <- as.factor(IEA_limpio$region)

# Realizar análisis de regresión lineal
modelo <- lm(emissions ~ region, data = IEA_limpio)

# Resumen del modelo
summary(modelo)
```

Tablas de resumen para tener solo 2 variables
```{r}
IEA_limpio$country <- as.factor(IEA_limpio$country) #Paises como factor

#Dataframe con la suma de emisiones de cada tipo de fuente, para cada país
sumas_pais <- IEA_limpio %>% group_by(country, type) %>% 
  summarise("emi" = sum(emissions))

#Dataframe solo con país y región, sin duplicados
pais_region <- IEA_limpio[c(1,2)]
pais_region <- pais_region[!duplicated(pais_region$country),]

#Agregar la region correspondiente a cada pais en tabla de sumas

sumas_pais <- pais_region %>% inner_join(sumas_pais, by = "country", keep = F)

sumas_pais
```

```{r}
#Gráfico de dispersión del dataframe de sumas
sumas_pais <- sumas_pais[sumas_pais$type!="Other", ]

ggplot(data = sumas_pais, aes(emi, region, colour = type)) +
  geom_jitter(height = 0, width = .4) +
  scale_x_continuous(trans="log10") #Escala logaritmica del eje x

##No sé si dejarla porque en realidad no se puede interpretar mucho de ella.
```





